set -g mouse on
set -g set-clipboard on
# integration with vim
set -sg escape-time 0
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# copy mode uses vim keys
set -g mode-keys vi
# 2. Use 'v' to begin selection (like visual mode in Vim)
bind-key -T copy-mode-vi v send-keys -X begin-selection

# 3. Use 'y' to yank the selection to the system clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# 4. Optional: Drag to copy with mouse (if mouse mode is on)
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# numbers starting at 1
set -g base-index 1
set -g pane-base-index 1

# ` as leader
unbind C-b
set -g prefix `
bind ` send-prefix
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# ==== Look and Feel ======
# full color spectrum
# Tell tmux to use 256-color mode by default
set -g default-terminal "tmux-256color"
# Force tmux to enable True Color (RGB) support for your terminal
# (This line matches standard xterm, alacritty, kitty, and iTerm2 profiles)
set -as terminal-features ",xterm-256color:RGB"

# status bar at the top
set -g status-position top
set -g status-justify center

# date and time in the bar
set -g status-right "%Y-%m-%d %H:%M"

# nice color scheme
# TODO: Make background clear
# TODO: only change text color on active window only
#One dark
set -g status-style "bg=#282c34,fg=#abb2bf"
set -g window-status-current-style "bg=#61afef,fg=#1e1e24,bold"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "

# TODO: prompt for a window name
# TODO: fix lettering of session

# window renumber
set -g renumber-windows on
